---
kind: pipeline
name: apps/player

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'apps/player/**/*.{js,vue}'

- name: integration
  image: cypress/included:8.5.0
  commands:
    - npx cypress install
    - npx lerna run player:start --scope @podlove/player --stream > http.log 2>&1 &
    - npx lerna run test:ci --scope @podlove/player --stream

- name: build
  image: node:14
  commands:
    - npx lerna run build --scope @podlove/player --stream

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/player --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: apps/player/publish
  when:
    ref:
    - refs/tags/v*


---
kind: pipeline
name: apps/web-player

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'apps/web-player/**/*.{js,vue}'

- name: integration
  image: cypress/included:8.5.0
  commands:
    - npx cypress install
    - npx lerna run integration:build --scope @podlove/web-player --stream
    - npx lerna run integration:server --scope @podlove/web-player --stream
    - npx lerna run integration:ci --scope @podlove/web-player --stream

- name: build
  image: node:14
  commands:
    - npx lerna run build --scope @podlove/web-player --stream

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/web-player --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: apps/web-player/publish
  when:
    ref:
    - refs/tags/v*

- name: cdn:prepare
  image: node:14
  commands:
    - rm -rf apps/web-player/publish
    - npx lerna run build:cdn --scope @podlove/web-player --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:cdn
  image: instrumentisto/rsync-ssh
  environment:
    PRIVATE_KEY:
      from_secret: PRIVATE_CDN_KEY
    PUBLIC_KEY:
      from_secret: PUBLIC_CDN_KEY
  commands:
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY" >> ~/.ssh/id_rsa
    - echo "$PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - ssh-keyscan rsync.keycdn.com >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa.pub
    - rsync -rvt --chmod=D2755,F644 apps/web-player/dist/ podlove@rsync.keycdn.com:applications/web-player/5.x/
  when:
    ref:
    - refs/tags/v*

---
kind: pipeline
name: apps/subscribe-button

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'apps/subscribe-button/**/*.{js,vue}'

- name: build
  image: node:14
  commands:
    - npx lerna run build --scope @podlove/subscribe-button --stream

---
kind: pipeline
name: packages/components

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/components/**/*.{js,vue}'

- name: test
  image: node:14
  commands:
    - npx jest packages/components

- name: build
  image: node:14
  commands:
    - npx lerna run build --scope @podlove/components --stream

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/components --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/components/publish
  when:
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/player-actions

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/player/actions/**/*.{js,vue}'

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/actions
  when:
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/player-sagas

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/player/sagas/**/*.{js,vue}'

- name: test
  image: node:14
  commands:
    - npx jest 'packages/player/sagas'

- name: build
  image: node:14
  commands:
    - npx lerna run build --scope @podlove/player-sagas --stream

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/sagas
  when:
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/player-state

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/player/state/**/*.{js,vue}'

- name: test
  image: node:14
  commands:
    - npx jest 'packages/player/state'

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/state
  when:
    ref:
    - refs/tags/v*

---
  kind: pipeline
  name: packages/player-config

  steps:
  - name: bootstrap
    image: node:14
    commands:
      - npm set unsafe-perm true
      - npm i
      - npx lerna bootstrap --hoist

  - name: lint
    image: node:14
    commands:
      - npx eslint 'packages/player/config/**/*.{js,vue}'

  - name: test
    image: node:14
    commands:
      - npx jest 'packages/player/config'

  - name: deploy:npm
    image: plugins/npm
    failure: ignore
    settings:
      username: alexander-heimbuch
      token:
        from_secret: NPM_TOKEN
      email: npm@heimbu.ch
      folder: packages/player/config
    when:
      ref:
      - refs/tags/v*

---
kind: pipeline
name: packages/player-react

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/player/react/**/*.{js,jsx}'

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/player-react --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/react/publish
  when:
    ref:
    - refs/tags/v*

---
kind: pipeline
name: packages/utils

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/utils/**/*.{js,vue}'

- name: test
  image: node:14
  commands:
    - npx jest 'packages/utils'

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/utils --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/utils/publish
  when:
    ref:
    - refs/tags/v*

---
kind: pipeline
name: packages/clients

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/clients/**/*.js'

- name: build
  image: node:14
  commands:
    - npx lerna run build --scope @podlove/clients --stream

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/clients --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/clients/publish
  when:
    ref:
    - refs/tags/v*

---
kind: pipeline
name: packages/button-actions

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/button/actions/**/*.{js,vue}'

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/button/actions
  when:
    ref:
    - refs/tags/v*

---
kind: pipeline
name: packages/button-react

steps:
- name: bootstrap
  image: node:14
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:14
  commands:
    - npx eslint 'packages/button/react/**/*.{js,jsx}'

- name: release:prepare
  image: node:14
  commands:
    - npx lerna run publish:prepare --scope @podlove/button-react --stream
  when:
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  failure: ignore
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/button/react/publish
  when:
    ref:
    - refs/tags/v*
