---
kind: pipeline
name: apps/player

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'apps/player/**/*.{js,vue}'

- name: integration
  image: cypress/base:10
  commands:
    - npx cypress install
    - npx lerna run integration:build --scope @podlove/player
    - npx lerna run integration:server --scope @podlove/player
    - npx lerna run integration:ci --scope @podlove/player

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/player

- name: release:prepare
  image: node:10
  commands:
    - npx lerna run publish:prepare --scope @podlove/player
  when:
    branch:
    - master
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: apps/player/publish
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: apps/web-player

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'apps/web-player/**/*.{js,vue}'

- name: integration
  image: cypress/base:10
  commands:
    - npx cypress install
    - npx lerna run integration:build --scope @podlove/web-player
    - npx lerna run integration:server --scope @podlove/web-player
    - npx lerna run integration:ci --scope @podlove/web-player

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/web-player

- name: release:prepare
  image: node:10
  commands:
    - npx lerna run publish:prepare --scope @podlove/web-player
  when:
    branch:
    - master
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: apps/web-player/publish
  when:
    branch:
    - master
    ref:
    - refs/tags/v*

- name: cdn:prepare
  image: node:10
  commands:
    - npx lerna run build:cdn --scope @podlove/web-player
  when:
    branch:
    - master
    ref:
    - refs/tags/v*

- name: deploy:cdn
  image: drillster/drone-rsync
  settings:
    hosts: [ "rsync.keycdn.com" ]
    user: podlove
    key:
      from_secret: CDN_KEY
    source: ./apps/web-player/dist
    target: applications/web-player/
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/components

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/components/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest packages/components

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/components

- name: release:prepare
  image: node:10
  commands:
    - npx lerna run publish:prepare --scope @podlove/components
  when:
    branch:
    - master
    ref:
    - refs/tags/v*

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/components/publish
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/player-actions

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/player/actions/**/*.{js,vue}'

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/actions
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/player-sagas

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/player/sagas/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest 'packages/player/sagas'

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/player-sagas

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/sagas
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/player-state

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/player/state/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest 'packages/player/state'

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/player/state
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: packages/utils

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/utils/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest 'packages/utils'

- name: deploy:npm
  image: plugins/npm
  settings:
    username: alexander-heimbuch
    token:
      from_secret: NPM_TOKEN
    email: npm@heimbu.ch
    folder: packages/utils
  when:
    branch:
    - master
    ref:
    - refs/tags/v*


---
kind: pipeline
name: docs/web-player

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/docs-web-player

- name: deploy:github
  image: node:10
  commands:
    - npx lerna run publish --scope @podlove/docs-web-player
  when:
    branch:
    - master
    ref:
    - refs/tags/v*
