/**
 * @see https://github.com/podlove/podlove-ui/blob/development/packages/player/actions/types.js
 */
export type PodloveWebPlayerStoreActionType =
  // Lifecycle
  | "PLAYER_CONSTRUCTED" // config was parsed
  | "PLAYER_INIT" // initial config
  | "PLAYER_READY" // config was parsed
  | "PLAYER_RESTORE" // restored

  // Chapters
  | "PLAYER_SET_CHAPTERS_LIST"
  | "PLAYER_NEXT_CHAPTER"
  | "PLAYER_PREVIOUS_CHAPTER"
  | "PLAYER_SET_CHAPTER"
  | "PLAYER_UPDATE_CHAPTER"

  // Steppers
  | "PLAYER_STEP_FORWARD"
  | "PLAYER_STEP_BACKWARDS"

  // Components => internal
  | "PLAYER_SHOW_COMPONENT_INFO"
  | "PLAYER_SHOW_COMPONENT_SHOW_TITLE"
  | "PLAYER_SHOW_COMPONENT_EPISODE_TITLE"
  | "PLAYER_SHOW_COMPONENT_SUBTITLE"
  | "PLAYER_SHOW_COMPONENT_INFO_POSTER"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_CHAPTERS"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_STEPPERS"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_LOADING"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_REPLAY"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_REMAINING"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_DURATION"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_RETRY"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_PLAYING"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON_PAUSE"
  | "PLAYER_SHOW_COMPONENT_PROGRESSBAR"
  | "PLAYER_SHOW_COMPONENT_TAB"
  | "PLAYER_SHOW_COMPONENT_VOLUME_SLIDER"
  | "PLAYER_SHOW_COMPONENT_RATE_SLIDER"
  | "PLAYER_SHOW_COMPONENT_CHANNELS"
  | "PLAYER_SHOW_COMPONENT_CONTROLS_BUTTON"
  | "PLAYER_HIDE_COMPONENT_INFO"
  | "PLAYER_HIDE_COMPONENT_SHOW_TITLE"
  | "PLAYER_HIDE_COMPONENT_EPISODE_TITLE"
  | "PLAYER_HIDE_COMPONENT_SUBTITLE"
  | "PLAYER_HIDE_COMPONENT_INFO_POSTER"
  | "PLAYER_HIDE_COMPONENT_ERROR"
  | "PLAYER_HIDE_COMPONENT_CONTROLS_CHAPTERS"
  | "PLAYER_HIDE_COMPONENT_CONTROLS_STEPPERS"
  | "PLAYER_HIDE_COMPONENT_CONTROLS_BUTTON"
  | "PLAYER_HIDE_COMPONENT_PROGRESSBAR"
  | "PLAYER_HIDE_COMPONENT_TAB"
  | "PLAYER_HIDE_COMPONENT_VOLUME_SLIDER"
  | "PLAYER_HIDE_COMPONENT_RATE_SLIDER"
  | "PLAYER_HIDE_COMPONENT_CHANNELS"

  // Visible Components => external
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_INFO"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_CHAPTERS"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_FILES"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_AUDIO"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_SHARE"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_TRANSCRIPTS"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_TAB_PLAYLIST"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_HEADER_POSTER"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_HEADER_TITLE"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_HEADER_EPISODE"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_HEADER_SUBTITLE"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_CONTROLS_STEPPER"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_CONTROLS_CHAPTERS"
  | "PLAYER_SHOW_VISIBLE_COMPONENTS_CONTROLS_PROGRESSBAR"
  | "PLAYER_SHOW_SHARE_PLAYTIME"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_INFO"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_CHAPTERS"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_FILES"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_AUDIO"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_SHARE"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_TRANSCRIPTS"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_TAB_PLAYLIST"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_HEADER_POSTER"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_HEADER_TITLE"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_HEADER_EPISODE"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_HEADER_SUBTITLE"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_CONTROLS_STEPPER"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_CONTROLS_CHAPTERS"
  | "PLAYER_HIDE_VISIBLE_COMPONENTS_CONTROLS_PROGRESSBAR"
  | "PLAYER_HIDE_SHARE_PLAYTIME"

  // Error
  | "PLAYER_BACKEND_ERROR"
  | "PLAYER_NETWORK_EMPTY"
  | "PLAYER_NETWORK_NO_SOURCE"
  | "PLAYER_ERROR_MISSING_AUDIO_FILES"
  | "PLAYER_ERROR_POSTER_LOAD"

  // Progress
  | "PLAYER_SIMULATE_PLAYTIME"
  | "PLAYER_ENABLE_GHOST_MODE"
  | "PLAYER_DISABLE_GHOST_MODE"

  // Player
  | "PLAYER_REQUEST_PLAY"
  | "PLAYER_BACKEND_PLAY"
  | "PLAYER_REQUEST_PAUSE"
  | "PLAYER_BACKEND_PAUSE"
  | "PLAYER_REQUEST_RESTART"
  | "PLAYER_BACKEND_BUFFER"
  | "PLAYER_STOP"
  | "PLAYER_IDLE"
  | "PLAYER_BACKEND_LOADING_START"
  | "PLAYER_BACKEND_LOADING_END"
  | "PLAYER_REQUEST_LOAD"
  | "PLAYER_LOADED"
  | "PLAYER_BACKEND_END"

  // Audio
  | "PLAYER_MUTE"
  | "PLAYER_UNMUTE"
  | "PLAYER_SET_VOLUME"
  | "PLAYER_SET_RATE"

  // Timepiece
  | "PLAYER_BACKEND_DURATION"
  | "PLAYER_BACKEND_PLAYTIME"
  | "PLAYER_REQUEST_PLAYTIME"
  | "PLAYER_UPDATE_PLAYTIME"
  | "PLAYER_BACKEND_LIVESYNC"

  // Quantiles
  | "PLAYER_LOAD_QUANTILES"
  | "PLAYER_SET_QUANTILE"

  // Runtime
  | "PLAYER_SET_RUNTIME"
  | "PLAYER_SET_LANGUAGE"
  | "PLAYER_SET_VERSION"
  | "PLAYER_SET_MODE"

  // Share
  | "PLAYER_SELECT_CONTENT"
  | "PLAYER_SELECT_CHANNEL"
  | "PLAYER_SELECT_EMBED_SIZE"

  // Tabs
  | "PLAYER_TOGGLE_TAB"
  | "PLAYER_SET_TABS"

  // Theme
  | "PLAYER_SET_THEME"

  // Transcripts
  | "PLAYER_SET_TRANSCRIPTS_TIMELINE"
  | "PLAYER_UPDATE_TRANSCRIPTS"
  | "PLAYER_TOGGLE_FOLLOW_TRANSCRIPTS"
  | "PLAYER_SEARCH_TRANSCRIPTS"
  | "PLAYER_SET_SEARCH_TRANSCRIPTS_RESULTS"
  | "PLAYER_NEXT_SEARCH_RESULT"
  | "PLAYER_PREVIOUS_SEARCH_RESULT"
  | "PLAYER_RESET_SEARCH_TRANSCRIPTS"

  // Error
  | "PLAYER_SHOW_ERROR"
  | "PLAYER_HIDE_ERROR"
  | "PLAYER_RETRY_PLAY"
  | "PLAYER_ERROR_CONFIG_MEDIA"
  | "PLAYER_ERROR_CONFIG_MISSING"

  // Keyboard
  | "PLAYER_KEY_UP"
  | "PLAYER_KEY_DOWN"

  // Playlist
  | "PLAYER_NEXT_PLAYLIST_ENTRY"
  | "PLAYER_SELECT_PLAYLIST_ENTRY"
  | "PLAYER_MARK_PLAYLIST_ENTRY_ACTIVE"

  // Files
  | "PLAYER_FILE_HOVER"
  | "PLAYER_FILE_SELECT";
