export const INIT = 'BUTTON_INIT'

export const SHOW_LIST = 'BUTTON_SHOW_LIST'
export const HIDE_LIST = 'BUTTON_HIDE_LIST'

export const SHOW_OVERLAY = 'BUTTON_SHOW_OVERLAY'
export const HIDE_OVERLAY = 'BUTTON_HIDE_OVERLAY'

export const SHOW_FINISH_CARD = 'BUTTON_SHOW_FINISH_CARD'
export const HIDE_FINISH_CARD = 'BUTTON_HIDE_FINISH_CARD'
