import { createAction } from 'redux-actions'

import {
  SHOW_VISIBLE_COMPONENTS_TAB_INFO,
  SHOW_VISIBLE_COMPONENTS_TAB_CHAPTERS,
  SHOW_VISIBLE_COMPONENTS_TAB_FILES,
  SHOW_VISIBLE_COMPONENTS_TAB_AUDIO,
  SHOW_VISIBLE_COMPONENTS_TAB_SHARE,
  SHOW_VISIBLE_COMPONENTS_TAB_TRANSCRIPTS,
  SHOW_VISIBLE_COMPONENTS_HEADER_POSTER,
  SHOW_VISIBLE_COMPONENTS_HEADER_TITLE,
  SHOW_VISIBLE_COMPONENTS_HEADER_EPISODE,
  SHOW_VISIBLE_COMPONENTS_HEADER_SUBTITLE,
  SHOW_VISIBLE_COMPONENTS_CONTROLS_STEPPER,
  SHOW_VISIBLE_COMPONENTS_CONTROLS_CHAPTERS,
  SHOW_VISIBLE_COMPONENTS_CONTROLS_PROGRESSBAR,
  SHOW_SHARE_PLAYTIME,
  HIDE_VISIBLE_COMPONENTS_TAB_INFO,
  HIDE_VISIBLE_COMPONENTS_TAB_CHAPTERS,
  HIDE_VISIBLE_COMPONENTS_TAB_FILES,
  HIDE_VISIBLE_COMPONENTS_TAB_AUDIO,
  HIDE_VISIBLE_COMPONENTS_TAB_SHARE,
  HIDE_VISIBLE_COMPONENTS_TAB_TRANSCRIPTS,
  HIDE_VISIBLE_COMPONENTS_HEADER_POSTER,
  HIDE_VISIBLE_COMPONENTS_HEADER_TITLE,
  HIDE_VISIBLE_COMPONENTS_HEADER_EPISODE,
  HIDE_VISIBLE_COMPONENTS_HEADER_SUBTITLE,
  HIDE_VISIBLE_COMPONENTS_CONTROLS_STEPPER,
  HIDE_VISIBLE_COMPONENTS_CONTROLS_CHAPTERS,
  HIDE_VISIBLE_COMPONENTS_CONTROLS_PROGRESSBAR,
  HIDE_SHARE_PLAYTIME
} from './types.js'

// Tabs
export const showInfoTab = createAction<void>(SHOW_VISIBLE_COMPONENTS_TAB_INFO)
export const hideInfoTab = createAction<void>(HIDE_VISIBLE_COMPONENTS_TAB_INFO)
export const showChaptersTab = createAction<void>(SHOW_VISIBLE_COMPONENTS_TAB_CHAPTERS)
export const hideChaptersTab = createAction<void>(HIDE_VISIBLE_COMPONENTS_TAB_CHAPTERS)
export const showFilesTab = createAction<void>(SHOW_VISIBLE_COMPONENTS_TAB_FILES)
export const hideFilesTab = createAction<void>(HIDE_VISIBLE_COMPONENTS_TAB_FILES)
export const showAudioTab = createAction<void>(SHOW_VISIBLE_COMPONENTS_TAB_AUDIO)
export const hideAudioTab = createAction<void>(HIDE_VISIBLE_COMPONENTS_TAB_AUDIO)
export const showShareTab = createAction<void>(SHOW_VISIBLE_COMPONENTS_TAB_SHARE)
export const hideShareTab = createAction<void>(HIDE_VISIBLE_COMPONENTS_TAB_SHARE)
export const showTranscriptsTab = createAction<void>(SHOW_VISIBLE_COMPONENTS_TAB_TRANSCRIPTS)
export const hideTranscriptsTab = createAction<void>(HIDE_VISIBLE_COMPONENTS_TAB_TRANSCRIPTS)

// Header
export const showInfoPoster = createAction<void>(SHOW_VISIBLE_COMPONENTS_HEADER_POSTER)
export const hideInfoPoster = createAction<void>(HIDE_VISIBLE_COMPONENTS_HEADER_POSTER)
export const showShowTitle = createAction<void>(SHOW_VISIBLE_COMPONENTS_HEADER_TITLE)
export const hideShowTitle = createAction<void>(HIDE_VISIBLE_COMPONENTS_HEADER_TITLE)
export const showEpisodeTitle = createAction<void>(SHOW_VISIBLE_COMPONENTS_HEADER_EPISODE)
export const hideEpisodeTitle = createAction<void>(HIDE_VISIBLE_COMPONENTS_HEADER_EPISODE)
export const showSubtitle = createAction<void>(SHOW_VISIBLE_COMPONENTS_HEADER_SUBTITLE)
export const hideSubtitle = createAction<void>(HIDE_VISIBLE_COMPONENTS_HEADER_SUBTITLE)

// Controls
export const showChapterControls = createAction<void>(SHOW_VISIBLE_COMPONENTS_CONTROLS_CHAPTERS)
export const hideChapterControls = createAction<void>(HIDE_VISIBLE_COMPONENTS_CONTROLS_CHAPTERS)
export const showSteppersControls = createAction<void>(SHOW_VISIBLE_COMPONENTS_CONTROLS_STEPPER)
export const hideSteppersControls = createAction<void>(HIDE_VISIBLE_COMPONENTS_CONTROLS_STEPPER)
export const showProgressBar = createAction<void>(SHOW_VISIBLE_COMPONENTS_CONTROLS_PROGRESSBAR)
export const hideProgressBar = createAction<void>(HIDE_VISIBLE_COMPONENTS_CONTROLS_PROGRESSBAR)

// Share
export const showSharePlaytime = createAction<void>(SHOW_SHARE_PLAYTIME)
export const hideSharePlaytime = createAction<void>(HIDE_SHARE_PLAYTIME)
