export const INIT = 'INIT'
export const SET_METADATA = 'SET_METADATA'
export const TOGGLE_TAB = 'TOGGLE_TAB'

export const SHOW_INFO = 'SHOW_INFO'
export const HIDE_INFO = 'HIDE_INFO'

export const SHOW_OVERLAY = 'SHOW_OVERLAY'
export const HIDE_OVERLAY = 'HIDE_OVERLAY'

export const SHOW_FINISH_SCREEN = 'SHOW_FINISH_SCREEN'
export const CLOSE_FINISH_SCREEN = 'CLOSE_FINISH_SCREEN'

export const FILL_FINISH_OBJECT = 'FILL_FINISH_OBJECT'
export const RESET_FINISH_OBJECT = 'RESET_FINISH_OBJECT'
