name: Release
on:
  push:
    tags:
      - '*'

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm set unsafe-perm true
      - run: npm ci
      - run: npx lerna bootstrap --hoist

  apps_player:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci

      - name: release:prepare
        run: npx lerna run publish:prepare --scope @podlove/player --stream

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: apps/player/publish

  apps_web-player:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'

    - name: install
      run: npm ci

    - name: release:prepare
      run: npx lerna run publish:prepare --scope @podlove/web-player --stream

    - name: publish:npm
      uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: apps/web-player/publish

    - name: cdn:prepare
      run: |
        rm -rf apps/web-player/publish
        npx lerna run build:cdn --scope @podlove/web-player --stream

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: checkout repo
      run: git clone git@github.com:podlove/cdn.git cdn

    - name: config
      run: |
        git config --global user.email "ci@github.com"
        git config --global user.name "CI"

    - name: publish:cdn
      run: |
        cp -R apps/web-player/dist/* cdn/web-player/5.x/
        ls -la cdn/web-player/5.x/
        cd cdn
        git add .
        git commit -m "ci: upgrade cdn"
        git push origin

  packages_components:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci

      - name: release:prepare
        run: npx lerna run publish:prepare --scope @podlove/components --stream

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/components/publish

  packages_player-actions:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/player/actions

  packages_player-state:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/player/actions

  packages_player-config:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/player/config

  packages_utils:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci

      - name: release:prepare
        run: npx lerna run publish:prepare --scope @podlove/utils --stream

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/utils/publish

  packages_clients:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci

      - name: release:prepare
        run: npx lerna run publish:prepare --scope @podlove/clients --stream

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/clients/publish

  packages_button-actions:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/button/actions

  packages_player-react:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci

      - name: release:prepare
        run: npx lerna run publish:prepare --scope @podlove/player-react --stream

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/player/react/publish

  packages_button-react:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci

      - name: release:prepare
        run: npx lerna run publish:prepare --scope @podlove/button-react --stream

      - name: publish:npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/button/react/publish
